name: Img_Download


on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  schedule:
   - cron: '5 16 * * *'  # 本地时间每天的 1:00 执行
env:
    TZ: Asia/Shanghai

jobs:
   Img_download:
    runs-on: ubuntu-latest

    steps:
      - name: 检查环境
        uses: actions/checkout@v2
      - name: 设置环境
        run: |
           echo "folder_path=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: 运行脚本
        run: |
           file_folder=$(date "+%Y-%m-%d")
           # file_folder="2024-01-1"
           threshold=20
           if [ ! -d "$file_folder" ]; then
             mkdir "$file_folder"
           else 
             rm -rf  "$file_folder"
             mkdir "$file_folder"
           fi
           if [ ! -d img_name.txt ]; then
             touch img_name.txt
           fi
           main(){
               url="https://www.dmoe.cc/random.php?return=json"
               links=()
               counter=1
               while [ $counter -le $threshold ]
               do
                   response=$(curl -s "$url")
                   link=$(echo "$response" | jq -r '.imgurl')
                   file_name=$(basename "$link")
                   # 检查 img_name.txt 中是否存在相同的文件名，如果不存在则添加链接
                   if ! grep -q "$file_name" img_name.txt; then
                       links+=("$link")
                       echo "$file_name"
                       wget -q -P "$file_folder" -O "$file_folder/$file_name" -c "$link"
                       echo "$file_name" >> img_name.txt  # 添加新的文件名到 img_name.txt 文件
                   fi
                   ((counter++))
               done
           }
           main
           cdn_prefix="https://cdn.jsdelivr.net/gh/bgvioletsky/getimg"
           find . -type f -iname "*.jpg" | awk 'length($0) >= 13' | jq --arg prefix "$cdn_prefix" -R -s  '[split("\n")[] | select(. != "") | sub("^\\."; "") | $prefix + .]' > img_url.json
           find . -type f -iname "*.jpg" -exec basename {} \; | awk 'length($0) >= 13' >img_name.txt
           
      - name: 提交文件
        run: |
              git config --local user.email "44770157@qq.com"
              git config --local user.name "bgcode"
              git pull
              git add ${{ env.folder_path }}
              git add img_name.txt
              git add img_url.json
              git commit -m "update $(date +'%Y-%m-%d %H:%M:%S')"  
      - name:  推送文件
        uses:    ad-m/github-push-action@master
        with:  
           branch: main