name: Img_Download


on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  schedule:
   - cron: '5 16 * * *'  # 本地时间每天的 1:00 执行
env:
    TZ: Asia/Shanghai

jobs:
   Img_download:
    runs-on: ubuntu-latest

    steps:
      - name: 检查环境
        uses: actions/checkout@v2
      - name: 设置环境
        run: |
           wget https://raw.githubusercontent.com/bgvioletsky/commod/main/getimg.sh
           echo "folder_path=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: 运行脚本
        run: |
           bash -c "$(curl -fsSL https://raw.githubusercontent.com/bgvioletsky/commod/main/getimg.sh)"
           cdn_prefix="https://cdn.jsdelivr.net/gh/bgvioletsky/testaction"
           find . -type f -iname "*.jpg" | awk 'length($0) >= 13' | jq --arg prefix "$cdn_prefix" -R -s  '[split("\n")[] | select(. != "") | sub("^\\."; "") | $prefix + .]' > img_url.json
           find . -type f -iname "*.jpg" -exec basename {} \; | awk 'length($0) >= 13' >img_name.txt
           
      - name: 提交文件
        run: |
              git config --local user.email "44770157@qq.com"
              git config --local user.name "bgcode"
              git pull
              git add ${{ env.folder_path }}
              git add img_name.txt
              git add img_url.json
              git commit -m "update $(date +'%Y-%m-%d %H:%M:%S')"  
      - name:  推送文件
        uses:    ad-m/github-push-action@master
        with:  
           branch: main