name: Display Input Value

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: $(date "+%Y-%m-%d")

jobs:
  display_input:
    runs-on: ubuntu-latest
    steps:
      - name: Display input value
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
